### ISSUE TITLE
Coveralls PR check bot broken

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#208] opened 2015-07-03 07:05 UTC
Quoting from https://github.com/OCA/partner-contact/issues/136#issue-92588674:

> As stated in https://github.com/OCA/partner-contact/pull/104#issuecomment-117522275, the Coveralls check for PR seems to be broken. Currently only 1 LOC is not tested in that PR, and see what [the bot says](https://coveralls.io/builds/2957735):

> ![captura de pantalla de 2015-07-02 11-00-19](https://cloud.githubusercontent.com/assets/973709/8473504/68bc78ce-20aa-11e5-9d57-31cf70b04fd4.png)

> It seems bot's bug.

**Comment by dreispt** [comment] 2015-07-03 08:28
Coverage is measuring the full repo, not only module.
If your module keeps same coverage, but total repo LOC decreases, the global coverage % can decrease.

**Comment by Yajo** [comment] 2015-07-03 09:28
I finally understand! But anyway seems a bug, and having that red X mark can prevent reviewers from reviewing the PR, don't you think? Is there nothing that can be done on that?

**Comment by dreispt** [comment] 2015-07-03 10:10
I agree that marking a failed build when coverage decreases can be over-zealous.
It was not always the case - that's a recent behaviour. 
I don't know if we can - or want to - change that.

**Comment by Yajo** [comment] 2015-07-03 10:21
Mostly when in some cases it's not real. As code moves to the new api, it's easy that size decreases and this bug keeps replicating.

**Comment by pedrobaeza** [comment] 2015-07-03 11:39
The problem is that the tested code is the one who decreases, not the untested one. As our goal is to have 100% coverage :stuck_out_tongue_winking_eye:, this is only a temporary problem. Out of jokes, knowing how to read this, there's no problem for reviewers. I can also put notes to guide people on this.

I close the issue. Maybe making a wiki page about this can be interesting.

**Closed by pedrobaeza** 2015-07-03 11:39 UTC

**Comment by bwrsandman** [comment] 2015-07-03 14:40
> Maybe making a wiki page about this can be interesting.

A note in CONTRIBUTING.md should be enough
