### ISSUE TITLE
Problem in several branches with Travis builds

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#509] opened 2017-11-09 16:47 UTC
On several branches, there are a problem with tests hanging up and raising Travis timeout error. Example: OCA/contract, 10.0 - https://travis-ci.org/OCA/contract/builds/299604289

I don't have right now more examples at hand, but there are more cases across PRs. In all of them, the message is:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Can you help?

**Comment by moylop260** [comment] 2017-11-09 17:01
Thanks you

**Comment by lasley** [comment] 2017-11-09 17:02
This one has been causing me a headache for months. Another example https://github.com/OCA/report-print-send/pull/95#issuecomment-324941786

**Comment by lasley** [comment] 2017-11-09 17:03
It likely stems from https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1888

**Comment by moylop260** [comment] 2017-11-09 17:25
In the past I had this same issue related with 2 stuffs:

1) Two databases at same time, because wkhtmltopdf don't send the database parameter and the webpage to get result is where your select database.
2) If the report webkit use a url to a css that don't exists.

I don't know what is the problem here for each project and this is so hard to debug because odoo don't show a output related with wkhtmltopdf because send `--silent` param.
So you need use pdb before of wkhtmltopdf command from odoo in order to reproduce it the same command in other terminal and see the real error.

I will do it that.

**Comment by moylop260** [comment] 2017-11-09 17:55
I remember a third stuff
If you try test a wkhtmltopdf report if is not a at_install(true) testing

**Comment by moylop260** [comment] 2017-11-10 05:15
For OCA/contract:10.0 the issue was the third stuff.
Testing wkhtmltopdf without at_install(true) the full description of the fix/issue is:
https://github.com/OCA/contract/pull/116

FYI this is not a MQT issue, this is a expected behaviour from odoo.

Now, I'll check report-print-send

**Comment by moylop260** [comment] 2017-11-10 05:17
I saw that OCA/report-print-send had the same third issue (not after install wkhtmltopdf test).
https://github.com/OCA/report-print-send/pull/95

Then I close this issue since that is not a MQT one.

**Closed by moylop260** 2017-11-10 05:17 UTC
Labels: bug

**Comment by moylop260** [comment] 2017-11-10 05:22
😆 
![pedro](https://user-images.githubusercontent.com/6644187/32644056-dbfd53ac-c5a4-11e7-8e2a-f42006f137ae.jpg)

**Comment by pedrobaeza** [comment] 2017-11-10 09:35
Thanks for your work debugging this, Moi, but I don't think it's a solution to change the features of the tests. I choose to use `SavepointCase` because one excellent feature: it doesn't execute for each test the setup, which can be more time consuming. Instead, it performs a rollback after each test to the previous status before beginning the test (via a savepoint). Changing to `HttpCase`, we are loosing that valuable possibility.

**Comment by moylop260** [comment] 2017-11-10 14:05
Hello Pedro,
Ok, you can create a mixer of features in the class in order to save time consuming without a feeze.
In this case I’m fixing the freeze.

Or you can create a issue to odoo in order to get the best solution for both worlds.
You feel free to change my pr or create other one
I just have created the PR of the guilty of the real problem (Dont MQT issue, Dont wkhtmltopdf issue)
Its a issue related with use a web server before to start it

**Comment by pedrobaeza** [comment] 2017-11-10 18:49
I don't get you. What is the issue then?

**Comment by lasley** [comment] 2017-11-10 20:21
Switching to `HttpCase` has been the solution in most of the timeout instances once we find the module. The reasoning is explaining in https://github.com/OCA/report-print-send/pull/95#issuecomment-325095885 (and the subsequent comment).

A TL;DR of the current analysis is that the HttpCase is setting [`enter_test_mode` and `leave_test_mode`](https://github.com/odoo/odoo/blob/10.0/odoo/modules/registry.py#L428-L444) which stops the registry lock:
```
File: "/home/alnsgara/Projects/demo/server/odoo/modules/registry.py", line 55, in __new__
  with cls._lock:
```

The problem to me is that this issue always gets merged and sits dormant in the repo for someone else to have to diagnose when it pops up. Trying to find a random module completely unrelated to the current PR while trying to diagnose the mystery timeout is causing a significant amount of our repos to stall development for a decent amount of time.

**Comment by moylop260** [comment] 2017-11-10 23:52
For me is so complex to explain it
But I have created a module to explain the issue with code 😆 
https://github.com/moylop260/freeze_tests_wo_httpcase_repo

Install the module and enable the tests locally (I used odoo 11.0 version)
After that uncomment the following line:
 -
 https://github.com/moylop260/freeze_tests_wo_httpcase_repo/blob/master/freeze_tests_wo_httpcase/tests/test_freeze_tests_wo_httpcase.py#L29


Tell me if is better to understand it

**Comment by moylop260** [comment] 2017-11-11 00:17
It is the same case for wkhtmltopdf using non-static urls.

For contract you can apply the following patch:
```diff
git diff 10.0-odoo
diff --git a/addons/report/models/report.py b/addons/report/models/report.py
index 0f7cf2201f0..d65341afc99 100644
--- a/addons/report/models/report.py
+++ b/addons/report/models/report.py
@@ -442,6 +442,8 @@ class Report(models.Model):
             try:
                 wkhtmltopdf = [_get_wkhtmltopdf_bin()] + command_args + local_command_args
                 wkhtmltopdf += [content_file_path] + [pdfreport_path]
+                print ' '.join(wkhtmltopdf)
+                import pdb;pdb.set_trace()
                 process = subprocess.Popen(wkhtmltopdf, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                 out, err = process.communicate()
```
And run the tests for a new database and new data_dir (no sessions)
Now, you can see the output for wkhtmltopdf command:

`/usr/local/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 40.0 --dpi 90 --header-spacing 35 --margin-left 7.0 --margin-bottom 20.0 --margin-right 7.0 --orientation Portrait --header-html /tmp/report.header.tmp.sIUwca.html --footer-html /tmp/report.footer.tmp.6sWUPW.html /tmp/report.body.tmp.y8kQ5x.html /tmp/report.tmp.xTaUJq.pdf`

If you run this command from other terminal removing `--quiet` parameter you will see the same hanging up:

 - <img width="1280" alt="wkhtmltopdf loading pages" src="https://user-images.githubusercontent.com/6644187/32683670-ac18245c-c642-11e7-847f-1f18eb427228.png">
(I just stoped the command with `ctrl+c`)


The files generated:
https://gist.github.com/moylop260/56c30167747d31c3316998db5a71c6f6
