### ISSUE TITLE
module name

### ISSUE THREAD

**Issue by bealdav** [OCA/maintainer-quality-tools#371] opened 2016-10-12 12:29 UTC
Hi, @moylop260 

We have a rule for module name as singular form but no check on it.

> Use of the singular form in module name (or use "multi"), except when compound of module name or object Odoo that is already in the plural (i.e. mrp_operations_...).

Could we add a check it only with v10 ?

a short list of exception could be provided: i.e. `logistics, etc.`

Thanks

**Comment by moylop260** [comment] 2016-10-12 15:14
This lint sound good to me
The question is if we wish renamed of modules for new versions to accomplish with this check.

**Comment by bealdav** [comment] 2016-10-12 15:55
Yes I think it's a good idea to rename impacted modules for 10 version.

Please @pedrobaeza  what do you think of that ?

Thanks

**Comment by pedrobaeza** [comment] 2016-10-12 16:41
Yes, for me it's also a good idea, and apply it to v10 modules. The problem is with extensions of core modules that contains the plural. For example: mrp_operations, hr_holidays. Maybe we can have a whitelist...

**Comment by bealdav** [comment] 2016-10-12 16:45
As far I know mrp_operations is no more in v10 with the refactor.

**Comment by pedrobaeza** [comment] 2016-10-12 16:48
But hr_holidays it is, and there are already proposed modules like hr_public_holidays or hr_holidays_compute_days

**Comment by bealdav** [comment] 2016-10-12 16:52
Maybe on next years, Odoo will fix their module names as they fixed some parts of coding syntax after OCA show pep8 and pylint.
Then we could consider to show the way again, and only authorise hr_holiday_blaba to have really few exception (i.e. logistics is not a plural, then a valid exception). 
I let you decide the better way. But we need to set this check quickly because of 'task force' effect ;-)

**Comment by bealdav** [comment] 2016-10-18 07:51
@moylop260 any news, about this rule with pedro mentionned exceptions ?
Thanks

**Comment by moylop260** [comment] 2016-10-18 12:33
@bealdav 
No, without news.
The status is Searching Help

If you want help use the following videos to learn
https://asciinema.org/a/26890
https://asciinema.org/a/26889

**Comment by nhomar** [comment] 2017-10-30 00:43
can we close this issue, I think it is under discussion yet and it can be referenced in the future but all Is all said here?

reopen it if needed.

**Closed by nhomar** 2017-10-30 00:43 UTC
